swagger: "2.0"
info:
  title: MoMo User API
  description: HTTP Service for accessing MTN's MoMo User API.
  termsOfService: https://github.com/wondenge/momo-go/blob/master/LICENCE
  contact:
    name: William Ondenge
    email: ondengew@gmail.com
    url: https://www.ondenge.me
  license:
    name: Apache License
    url: https://github.com/wondenge/momo-go/blob/master/LICENCE
  version: "1.0"
host: localhost:3000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /v1_0/apiuser/:
    post:
      tags:
      - user
      summary: createuser user
      description: Used to create an API user in the sandbox target environment
      operationId: user#createuser
      parameters:
      - name: ' X-Reference-Id'
        in: header
        description: Resource ID of the created request to pay transaction.
        required: true
        type: string
      - name: ' Ocp-Apim-Subscription-Key'
        in: header
        description: Subscription key which provides access to this API
        required: true
        type: string
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/UserCreateuserResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/UserCreateuserBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserCreateuserInternalErrorResponseBody'
      schemes:
      - http
  /v1_0/apiuser/{X-Reference-Id}:
    get:
      tags:
      - user
      summary: list user
      description: Used to get API user information.
      operationId: user#list
      parameters:
      - name: ' Ocp-Apim-Subscription-Key'
        in: header
        description: Subscription key which provides access to this API
        required: true
        type: string
      - name: ListRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserListRequestBody'
          required:
          - X-Reference-Id
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserListResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/UserListBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserListInternalErrorResponseBody'
      schemes:
      - http
  /v1_0/apiuser/{X-Reference-Id}/apikey:
    post:
      tags:
      - user
      summary: createkey user
      description: Used to create an API key for an API user in the sandbox target environment.
      operationId: user#createkey
      parameters:
      - name: ' Ocp-Apim-Subscription-Key'
        in: header
        description: Subscription key which provides access to this API
        required: true
        type: string
      - name: CreatekeyRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserCreatekeyRequestBody'
          required:
          - X-Reference-Id
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/UserCreatekeyResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/UserCreatekeyBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserCreatekeyInternalErrorResponseBody'
      schemes:
      - http
  /v1_0/apiuser/apiuser/{APIUser}:
    get:
      tags:
      - user
      summary: show user
      description: GET API User Details
      operationId: user#show
      parameters:
      - name: APIUser
        in: path
        description: API User.
        required: true
        type: string
      - name: ' Ocp-Apim-Subscription-Key'
        in: header
        description: Subscription key which provides access to this API
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserShowResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/UserShowBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserShowInternalErrorResponseBody'
      schemes:
      - http
definitions:
  UserCreatekeyBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: invalid data was sent in the request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserCreatekeyInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: check log for information (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserCreatekeyRequestBody:
    title: UserCreatekeyRequestBody
    type: object
    properties:
      X-Reference-Id:
        type: string
        description: Resource ID of the created request to pay transaction.
        example: c72025f5-5cd1-4630-99e4-8ba4722fad56
    example:
      X-Reference-Id: c72025f5-5cd1-4630-99e4-8ba4722fad56
    required:
    - X-Reference-Id
  UserCreatekeyResponseBody:
    title: 'Mediatype identifier: errorreason; view=default'
    type: object
    properties:
      code:
        type: string
        example: PAYER_NOT_FOUND
        enum:
        - PAYEE_NOT_FOUND
        - PAYER_NOT_FOUND
        - NOT_ALLOWED
        - NOT_ALLOWED_TARGET_ENVIRONMENT
        - INVALID_CALLBACK_URL_HOST
        - INVALID_CURRENCY
        - SERVICE_UNAVAILABLE
        - INTERNAL_PROCESSING_ERROR
        - NOT_ENOUGH_FUNDS
        - PAYER_LIMIT_REACHED
        - PAYEE_NOT_ALLOWED_TO_RECEIVE
        - PAYMENT_NOT_APPROVED
        - RESOURCE_NOT_FOUND
        - APPROVAL_REJECTED
        - EXPIRED
        - TRANSACTION_CANCELED
        - RESOURCE_ALREADY_EXIST
      message:
        type: string
        description: message
        example: Payee does not exist
    description: CreatekeyResponseBody result type (default view)
    example:
      code: PAYER_NOT_FOUND
      message: Payee does not exist
  UserCreateuserBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: invalid data was sent in the request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserCreateuserInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: check log for information (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserCreateuserResponseBody:
    title: 'Mediatype identifier: errorreason; view=default'
    type: object
    properties:
      code:
        type: string
        example: PAYER_NOT_FOUND
        enum:
        - PAYEE_NOT_FOUND
        - PAYER_NOT_FOUND
        - NOT_ALLOWED
        - NOT_ALLOWED_TARGET_ENVIRONMENT
        - INVALID_CALLBACK_URL_HOST
        - INVALID_CURRENCY
        - SERVICE_UNAVAILABLE
        - INTERNAL_PROCESSING_ERROR
        - NOT_ENOUGH_FUNDS
        - PAYER_LIMIT_REACHED
        - PAYEE_NOT_ALLOWED_TO_RECEIVE
        - PAYMENT_NOT_APPROVED
        - RESOURCE_NOT_FOUND
        - APPROVAL_REJECTED
        - EXPIRED
        - TRANSACTION_CANCELED
        - RESOURCE_ALREADY_EXIST
      message:
        type: string
        description: message
        example: Payee does not exist
    description: CreateuserResponseBody result type (default view)
    example:
      code: PAYER_NOT_FOUND
      message: Payee does not exist
  UserListBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: invalid data was sent in the request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserListInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: check log for information (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserListRequestBody:
    title: UserListRequestBody
    type: object
    properties:
      X-Reference-Id:
        type: string
        description: Resource ID of the created request to pay transaction.
        example: c72025f5-5cd1-4630-99e4-8ba4722fad56
    example:
      X-Reference-Id: c72025f5-5cd1-4630-99e4-8ba4722fad56
    required:
    - X-Reference-Id
  UserListResponseBody:
    title: 'Mediatype identifier: errorreason; view=default'
    type: object
    properties:
      code:
        type: string
        example: PAYER_NOT_FOUND
        enum:
        - PAYEE_NOT_FOUND
        - PAYER_NOT_FOUND
        - NOT_ALLOWED
        - NOT_ALLOWED_TARGET_ENVIRONMENT
        - INVALID_CALLBACK_URL_HOST
        - INVALID_CURRENCY
        - SERVICE_UNAVAILABLE
        - INTERNAL_PROCESSING_ERROR
        - NOT_ENOUGH_FUNDS
        - PAYER_LIMIT_REACHED
        - PAYEE_NOT_ALLOWED_TO_RECEIVE
        - PAYMENT_NOT_APPROVED
        - RESOURCE_NOT_FOUND
        - APPROVAL_REJECTED
        - EXPIRED
        - TRANSACTION_CANCELED
        - RESOURCE_ALREADY_EXIST
      message:
        type: string
        description: message
        example: Payee does not exist
    description: ListResponseBody result type (default view)
    example:
      code: PAYER_NOT_FOUND
      message: Payee does not exist
  UserShowBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: invalid data was sent in the request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserShowInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: check log for information (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserShowResponseBody:
    title: 'Mediatype identifier: errorreason; view=default'
    type: object
    properties:
      code:
        type: string
        example: PAYER_NOT_FOUND
        enum:
        - PAYEE_NOT_FOUND
        - PAYER_NOT_FOUND
        - NOT_ALLOWED
        - NOT_ALLOWED_TARGET_ENVIRONMENT
        - INVALID_CALLBACK_URL_HOST
        - INVALID_CURRENCY
        - SERVICE_UNAVAILABLE
        - INTERNAL_PROCESSING_ERROR
        - NOT_ENOUGH_FUNDS
        - PAYER_LIMIT_REACHED
        - PAYEE_NOT_ALLOWED_TO_RECEIVE
        - PAYMENT_NOT_APPROVED
        - RESOURCE_NOT_FOUND
        - APPROVAL_REJECTED
        - EXPIRED
        - TRANSACTION_CANCELED
        - RESOURCE_ALREADY_EXIST
      message:
        type: string
        description: message
        example: Payee does not exist
    description: ShowResponseBody result type (default view)
    example:
      code: PAYER_NOT_FOUND
      message: Payee does not exist
externalDocs:
  description: Library Usage
  url: https://github.com/wondenge/momo-go/blob/master/README.md
